name: Build and Maybe Release Image
run-name: ${{ startsWith(github.ref, 'refs/tags/v') && 'Build and Release Image' || 'Build Image' }}

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - v*

permissions: write-all # Necessary for the generate-build-provenance action with containers

jobs:
  release:
    uses: OpenCHAMI/github-actions/.github/workflows/go-build-release.yml@v3.2
    with:
      fetch-depth: 1
      pre-build-commands: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      goreleaser-version: "~> v2"
      attestation-binary-path: "dist/pcs_linux_amd64_v3/power-control, dist/pcs_linux_arm64_v8.0/power-control"
      registry-name: ghcr.io/openchami/pcs
